### ISSUE TITLE
openslide.lowlevel.OpenSlideUnsupportedFormatError: Unsupported or missing image file

### ISSUE THREAD

**Issue by koalary** [baidu-research/NCRF#24]
Traceback (most recent call last):
  File "NCRF/wsi/bin/patch_gen.py", line 80, in <module>
    main()
  File "NCRF/wsi/bin/patch_gen.py", line 76, in main
    run(args)
  File "NCRF/wsi/bin/patch_gen.py", line 71, in run
    pool.map(process, opts_list)
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 251, in map
    return self.map_async(func, iterable, chunksize).get()
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 567, in get
    raise self._value
openslide.lowlevel.OpenSlideUnsupportedFormatError: Unsupported or missing image file

could you please tell mo what is wrong?
Thanks!

**Comment by koalary** [comment]
(koalary) koalary@ubuntu:~/Camelyon16$ sudo python NCRF/wsi/bin/patch_gen.py Tumor_002.tif NCRF/coords/tumor_train.txt PATCHES_TUMOR_TRAIN/
Traceback (most recent call last):
  File "NCRF/wsi/bin/patch_gen.py", line 80, in <module>
    main()
  File "NCRF/wsi/bin/patch_gen.py", line 76, in main
    run(args)
  File "NCRF/wsi/bin/patch_gen.py", line 71, in run
    pool.map(process, opts_list)
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 251, in map
    return self.map_async(func, iterable, chunksize).get()
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 567, in get
    raise self._value
openslide.lowlevel.OpenSlideUnsupportedFormatError: Unsupported or missing image file

**Comment by koalary** [comment]
and I used openslide-python(1.1.1), could you please tell me what is wrong?
