### ISSUE TITLE
when I use probs_map.py, it will work,but when it will succeed,it report an error as following

### ISSUE THREAD

**Issue by zty12** [baidu-research/NCRF#44]
INFO:root:2020-05-25 00:44:36, flip : NONE, rotate : NONE, batch : 34369/36683, Run Time : 0.96
INFO:root:2020-05-25 00:44:37, flip : NONE, rotate : NONE, batch : 34370/36683, Run Time : 0.97
Traceback (most recent call last):
  File "NCRF/wsi/bin/probs_map.py", line 163, in <module>
    main()
  File "NCRF/wsi/bin/probs_map.py", line 159, in main
    run(args)
  File "NCRF/wsi/bin/probs_map.py", line 116, in run
    probs_map = get_probs_map(model, dataloader)
  File "NCRF/wsi/bin/probs_map.py", line 53, in get_probs_map
    for (data, x_mask, y_mask) in dataloader:
  File "D:\python\lib\site-packages\torch\utils\data\dataloader.py", line 264, in __next__
    batch = self.collate_fn([self.dataset[i] for i in indices])
  File "D:\python\lib\site-packages\torch\utils\data\dataloader.py", line 264, in <listcomp>
    batch = self.collate_fn([self.dataset[i] for i in indices])
  File "C:\Users\Administrator\Desktop\NCRF\NCRF\wsi\bin/../..\wsi\data\wsi_producer.py", line 85, in __getitem__
    (x, y), 0, (self._image_size, self._image_size)).convert('RGB')
  File "D:\python\lib\site-packages\openslide\__init__.py", line 223, in read_region
    level, size[0], size[1])
  File "D:\python\lib\site-packages\openslide\lowlevel.py", line 222, in read_region
    _read_region(slide, buf, x, y, level, w, h)
  File "D:\python\lib\site-packages\openslide\lowlevel.py", line 159, in _check_error
    raise OpenSlideError(err)
openslide.lowlevel.OpenSlideError: Not a JPEG file: starts with 0xff 0xc0

I have check my openslide:
C:\Users\Administrator>openslide-show-properties --version
openslide-show-properties.exe 3.4.1, using OpenSlide 3.4.1
Copyright (C) 2007-2015 Carnegie Mellon University and others

OpenSlide is free software: you can redistribute it and/or modify it under
the terms of the GNU Lesser General Public License, version 2.1.
<http://gnu.org/licenses/lgpl-2.1.html>

OpenSlide comes with NO WARRANTY, to the extent permitted by law.  See the
GNU Lesser General Public License for more details.

**Comment by yil8** [comment]
@zty12 sorry, but I've never tried NCRF on windows yet.
